#!/bin/sh
#
# http://github.com/darko-mesaros/dl
#
# simple downloader with curl
#
# req:
# curl
#

[ "$1" ] || { read -r inp && set "$inp" ; }

exec curl \
    --ipv4 \
    --disable \
    --location \
    --retry 2 \
    --continue-at - \
    --url "$1" \
    --output "${1##*/}"
    # --progress-bar \
