#!/bin/sh
#
# http://github.com/darko-mesaros/bin
#
# rain sounds from rainymood.com
# 
# req:
# youtube-dl
#


file=~/.cache/rain.ogg
url=http://rainymood.com

[ -f "$file" ] ||
youtube-dl -c --extract-audio --audio-quality 0 \
              --audio-format vorbis --prefer-ffmpeg \
              --no-playlist "$url" -o "$file"

exec play -l "$file"
