#!/bin/sh
#
# http://github.com/darko-mesaros/bin
#
# grab urls from piped input or stdin
#
# req:
# grep
#

prot='[a-zA-Z]+://'
host='[-a-zA-Z0-9._+]+'
path='[-a-zA-Z0-9._+#=?&:;%/!~()]+'

grep -Eo "$prot$host$path"
