#!/bin/sh
#
# http://github.com/darko-mesaros/bin
#
# search for and/or play youtube videos with mpv
# req: 
# youtube-dl
# mpv

case ${1#-} in
    h)
        >&2 echo 'Usage: yt [-s] [-m] [search terms]'
        exit 1
        ;;
    s)
        shift
        exec youtube-dl -e --default-search ytsearch8 \
            -- "$(printf '%s\n' "$*" | tr ' ' '+')"
        ;;
    m)
        shift
        MPV_OPTS="$MPV_OPTS --no-video"
        ;;
    x)
        shift
        MPV_OPTS="$MPV_OPTS --vo=caca"
esac

pkill -x vlc

# shellcheck disable=2086
youtube-dl ytsearch:"$(printf '%s\n' "$*" | tr ' ' '+')" | vlc -
#exec mpv $MPV_OPTS --no-loop \
#    --title="Hello Youtube" \
#    --script-opts=ytdl_hook-try_ytdl_first=yes \
#    -- ytdl://ytsearch:"$(printf '%s\n' "$*" | tr ' ' '+')"
